FROM ruby:alpine3.13

ARG UID

RUN adduser -D app -u ${UID:-1000} && \
  apk update \
  && apk add --no-cache gcc make libc-dev g++ mariadb-dev tzdata nodejs~=14 yarn mysql-client \
  && apk add less

WORKDIR /portfolio
COPY Gemfile .
COPY Gemfile.lock .
RUN bundle install
COPY --chown=app:app . /portfolio
RUN yarn install
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]

USER app
RUN mkdir -p tmp/sockets
RUN mkdir -p tmp/pids
