version: "3.9"

services:
  db:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      # MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - default
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
  redis:
    image: redis:alpine
    networks:
      - default
    ports:
      - '36379:6379'
  rails:
    build:
      context: .
      dockerfile: Dockerfile.ci
    ports:
      - '3000:3000'
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      # MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      # MYSQL_HOST: db
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: myapp_test
      REDIS_URL: "redis://redis:6379"
    depends_on:
      - db
      - redis
    networks:
      - default
    command: bundle exec rails server -b 0.0.0.0
