version: "3"

services:
  db:
    image: mysql:8.0.27
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - default
    ports:
      - '33306:3306'
    # command: --default-authentication-plugin=mysql_native_password
  redis:
    image: redis:alpine
    networks:
      - default
    ports:
      - '36379:6379'
  rails:
    build:
      context: .
      dockerfile: Dockerfile.ci
    container_name: rails
    ports:
      - '3000:3000'
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_HOST: db
      REDIS_URL: "redis://redis:6379"
    depends_on:
      - db
      - redis
    networks:
      - default
    command: bundle exec rails server -b 0.0.0.0
